### ISSUE TITLE
CustomStyles break RichTextEditor

### ISSUE THREAD

**Issue by rolandschuetz** [patriceckhart/NeosRulez.Neos.CkEditor.CustomStyles#1]
When I use a inpector rich text field, like:
```yaml
  properties:
    'html':
      type: string
      ui:
        label: i18n
        inspector:
          group: 'form'
          editor: 'Neos.Neos/Inspector/Editors/RichTextEditor'
```

The editor breaks with this message:
```
Name: TypeError

Message: Cannot read properties of undefined (reading 'customStyles')

Stacktrace:

TypeError: Cannot read properties of undefined (reading 'customStyles')
    at Object.isVisible (/_Resources/Static/Packages/NeosRulez.Neos.CkEditor.CustomStyles/Plugin.js?bust=9b04f8e8&e3171574:1783:23)
    at /_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:527:329
    at /_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:527:608
    at Array.filter (<anonymous>)
    at eu.renderToolbarComponents (/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:527:583)
    at eu.render (/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:527:1354)
    at jZ (/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:2:62143)
    at Rde (/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:2:61934)
    at Hpe (/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:4:9192)
    at Rpe (/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.js?bust=f09365d3&5110e4e7:4:866)

```

This can be fixed, by setting:
```yaml
  properties:
    'html':
      ui:
        inspector:
          editorOptions:
            customStyles: []
```

Probably `/Resources/Private/CustomStyles/src/manifest.js:49` should be changed to not break on undefined
